"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var chalk = require("chalk");
var name = ' => [suman-watch] => ';
exports.logInfo = console.log.bind(console, name);
exports.logGood = console.log.bind(console, chalk.cyan(name));
exports.logVeryGood = console.log.bind(console, chalk.green(name));
exports.logWarning = console.log.bind(console, chalk.yellow.bold(name));
exports.logError = console.log.bind(console, chalk.red(name));
var $exports = module.exports;
exports.default = $exports;
